routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', '\Nero\Evale\Http\Controllers\CompanyController@index')
    ->middleware('auth:company');

Route::prefix('admin')
    ->group(function () {
        $controller = '\Nero\Evale\Http\Controllers\AdminLoginController';
        Route::post('login', "{$controller}@login");
        Route::match(['get', 'head'], 'login', "{$controller}@showLoginForm")
            ->name('admin.login');
        Route::post('logout', "{$controller}@logout")
            ->name('admin.logout');
    });

Route::prefix('admin')
    ->middleware('auth:admin')
    ->group(function () {
        $controller = '\Nero\Evale\Http\Controllers\AdminController';
        Route::get('fillup', "{$controller}@fillUp")->name('admin.fillUp');
        Route::post('fillup', "{$controller}@postFillUp")->name('admin.postFillUp');
        Route::get('reports', "{$controller}@reports")->name('admin.reports');
    });

Route::resource(
    'admin',
    '\Nero\Evale\Http\Controllers\AdminController',
    ['parameters' => ['admin' => 'companyId']]
)->middleware('auth:admin');

Route::prefix('company')
    ->group(function () {
        $controller = '\Nero\Evale\Http\Controllers\CompanyLoginController';
        Route::post('login', "{$controller}@login");
        Route::match(['get', 'head'], 'login', "{$controller}@showLoginForm")
            ->name('company.login');
        Route::post('logout', "{$controller}@logout")
            ->name('company.logout');
    });

Route::prefix('company')
    ->middleware('auth:company')
    ->group(function () {
        $controller = '\Nero\Evale\Http\Controllers\CompanyController';
        Route::get('reports', "{$controller}@reports")->name('company.reports');
    });

Route::resource(
    'company',
    '\Nero\Evale\Http\Controllers\CompanyController',
    ['parameters' => ['company' => 'employeeId']]
)->middleware('auth:company');

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/admin/company.blade.php
@extends ('admin.layouts.main')

@section('page_heading','Empresa')

@section('section')

    <div class="col-sm-12">
        <div class="row">
            <div class="col-lg-12 margin-bottom-20">
                @isset($id)
                    <form role="form" action="{{ route('admin.update', $id) }}" method="post">
                @else
                    <form role="form" action="{{ route('admin.store') }}" method="post">
                @endisset

                    {{ csrf_field() }}

                    @isset($id)
                        {{ method_field('put') }}
                    @endisset

                    <div class="form-group">
                        <label for="name">Nome</label>
                        <input id="name" name="name" value="{{ $name ?? old('name') }}" class="form-control" maxlength="100" required>
                    </div>
                    <div class="form-group">
                        <label for="cnpj">CNPJ</label>
                        <input id="cnpj" name="cnpj" value="{{ $cnpj ?? old('cnpj') }}" class="form-control" maxlength="14" required>
                    </div>
                    <div class="form-group">
                        <label for="address">Endereço</label>
                        <input id="address" name="address" value="{{ $address ?? old('address') }}" class="form-control" maxlength="100">
                    </div>
                    <div class="form-group">
                        <label for="phone">Telefone</label>
                        <input id="phone" name="phone" value="{{ $phone ?? old('phone') }}" class="form-control" maxlength="11">
                    </div>
                    <div class="form-group">
                        <label for="subscription_limit">Limite de assinatura</label>
                        <div class="input-group">
                            <span class="input-group-addon">R$</span>
                            <input type="number" id="subscription_limit" name="subscription_limit" value="{{ $subscription_limit ?? old('subscription_limit') }}" class="form-control" step="0.01" min="1" max="100000" maxlength="6" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="login">Login</label>
                        <input id="login" name="login" value="{{ $login ?? old('login') }}" class="form-control" maxlength="10" required>
                    </div>
                    <div class="form-group">
                        <label for="password">Senha</label>
                        <input type="password" id="password" name="password" class="form-control" minlength="6" maxlength="8" {{ empty($id) ? 'required' : '' }}>
                    </div>
                    <div class="form-group">
                        <label for="password_confirmation">Confirmação de senha</label>
                        <input type="password" id="password_confirmation" name="password_confirmation" class="form-control" minlength="6" maxlength="8" {{ empty($id) ? 'required' : '' }}>
                    </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>
                    <a class="btn btn-default" href="{{ route('admin.index') }}">Cancelar</a>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/fillup.blade.php
@extends ('admin.layouts.main')

@section('page_heading','Abastecimento')

@section('section')

    @if(!$companies->count())

        <div class="alert alert-warning">Cadastre primeiramente uma empresa.</div>

    @else

        <div class="col-sm-12">
            <div class="row">
                <div class="col-lg-12 margin-bottom-20">
                    <form role="form" action="{{ route('admin.postFillUp') }}" method="post">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="fuel_type_id">Tipo</label>
                            <select id="fuel_type_id" name="fuel_type_id" class="form-control" required>
                                <option hidden selected value>Selecione...</option>
                                @foreach ($fuel_types ?? [] as $fuel_type)
                                    @php ($selected = old('fuel_type_id') == $fuel_type->id ? 'selected' : '')
                                    <option {{ $selected }} value="{{ $fuel_type->id }}">{{ $fuel_type->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="subscription_limit">Valor</label>
                            <div class="input-group">
                                <span class="input-group-addon">R$</span>
                                <input type="number" id="value" name="value" value="{{ $value ?? old('value') }}" class="form-control" step="0.01" min="1" max="100000" maxlength="6" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="company_id">Empresa</label>
                            <select id="company_id" name="company_id" class="form-control" required>
                                <option hidden selected value>Selecione...</option>
                                @foreach ($companies ?? [] as $company)
                                    @php ($selected = old('company_id') == $company->id ? 'selected' : '')
                                    <option {{ $selected }} value="{{ $company->id }}">{{ $company->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="employee_registration_number">Número de matrícula</label>
                            <input id="employee_registration_number" name="employee_registration_number" value="{{ $employee_registration_number ?? old('employee_registration_number') }}" class="form-control" maxlength="14" required>
                        </div>
                        <div class="form-group">
                            <label for="employee_password">Senha</label>
                            <input type="password" id="employee_password" name="employee_password" class="form-control" minlength="6" maxlength="8" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Lançar</button>
                        <a class="btn btn-default" href="{{ route('admin.index') }}">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>

    @endif

@endsection

resources/views/admin/index.blade.php
@extends('admin.layouts.main')

@section('page_heading','Dashboard')

@section('section')

    <div class="col-sm-12">
        <div class="row">
            <div class="col-lg-3 col-md-12">
                <div class="panel panel-yellow">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-briefcase fa-5x"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge">{{ $companiesCount }}</div>
                                <div>Empresas</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-file-text fa-5x"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge">
                                    {{ number_format($totalConsumption, 2, ',', '.') }}
                                </div>
                                <div>Total a receber</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-5 col-md-12">
                <div class="panel panel-green">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-usd fa-5x"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge">
                                    {{ number_format($subscriptionsTotal, 2, ',', '.') }}
                                </div>
                                <div>Crédito disponibilizado</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                @component('admin.widgets.panel')
                    @slot('panelTitle', 'Empresas')
                    @slot('panelBody')
                        @include('admin.widgets.index')
                    @endslot
                @endcomponent
            </div>
        </div>
    </div>

@endsection

resources/views/admin/layouts/main.blade.php
@extends('layouts.app')

@section('body')
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ route('admin.index') }}">
                    <img src="{{ asset('img/LOGO_ASSINATURA.svg') }}" class="navbar-logo">
                    <b>VALE</b>
                </a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> {{ ucwords(Auth::user()->name) }} <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="{{ route('admin.logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                                <i class="fa fa-sign-out fa-fw"></i> Logout
                            </a>
                        </li>
                        <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </ul>
                </li>
            </ul>

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li {{ (Request::is('*admin') ? 'class="active"' : '') }}>
                            <a href="{{ route('admin.index') }}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li {{ (Request::is('*create') ? 'class="active"' : '') }}>
                            <a href="{{ route('admin.create') }}"><i class="fa fa-edit fa-fw"></i> Cadastro empresa</a>
                        </li>
                        <li {{ (Request::is('*fillUp') ? 'class="active"' : '') }}>
                            <a href="{{ route('admin.fillUp') }}"><i class="fa fa-car fa-fw"></i> Abastecimento</a>
                        </li>
                        <li {{ (Request::is('*reports') ? 'class="active"' : '') }}>
                            <a href="{{ route('admin.reports') }}"><i class="fa fa-bar-chart-o fa-fw"></i> Transações</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">@yield('page_heading')</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>

            @if (session('info'))
                <div class="alert alert-info">
                    {{ session('info') }}
                </div>
            @endif

            @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif

            @if (session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
            @endif

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="row">
                @yield('section')
            </div>
            <!-- /#page-wrapper -->
        </div>
    </div>
@endsection

resources/views/admin/reports.blade.php
@extends('admin.layouts.main')

@section('page_heading','Transações')

@section('section')

    @include('admin.widgets.filter')

    <div class="col-sm-12">
        <div class="row">
            <div class="col-lg-5 col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-search fa-5x"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge">{{ $fillUpsCount }}</div>
                                <div>Registros</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-7 col-md-12">
                <div class="panel panel-green">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-usd fa-5x"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge">
                                    {{ number_format($totalConsumption, 2, ',', '.') }}
                                </div>
                                <div>Total</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                @component('admin.widgets.panel')
                    @slot('panelTitle', 'Empresas')
                    @slot('panelBody')
                        @include('admin.widgets.reports')
                    @endslot
                @endcomponent
            </div>
        </div>
    </div>

@endsection

resources/views/admin/widgets/filter.blade.php
<div class="col-sm-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <form role="form" method="get">
                <div class="form-group col-lg-4">
                    <label for="filterCompany">Empresa</label>
                    <select id="filterCompany" name="filter_company" class="form-control">
                        <option selected value>Todas</option>
                        @foreach ($filter['companies'] ?? [] as $company)
                            @php ($selected = request()->query('filter_company') == $company->id ? 'selected' : '')
                            <option {{ $selected }} value="{{ $company->id }}">{{ $company->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group col-lg-4">
                    <label for="filterInitial">Início</label>
                    <input type="date" id="filterInitial" name="filter_initial" value="{{ request()->query('filter_initial') ?: $filter['initial']->format('Y-m-d') }}" class="form-control">
                </div>
                <div class="form-group col-lg-4">
                    <label for="filterFinal">Fim</label>
                    <input type="date" id="filterFinal" name="filter_final" value="{{ request()->query('filter_final') ?: $filter['final']->format('Y-m-d') }}" class="form-control">
                </div>
                <div class="clearfix"></div>
                <div class="row">
                    <div class="col-lg-12 text-right">
                        <button type="submit" class="btn btn-default">Filtrar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/admin/widgets/index.blade.php
@if(!$companies->count())
    <div class="alert alert-info">Nenhum registro encontrado!</div>
@else
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th class="col-sm-6">Nome</th>
                    <th class="col-sm-2 text-right">Assinatura</th>
                    <th class="col-sm-2 text-right">Fatura atual</th>
                    <th class="col-sm-2"></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($companies as $company)
                    <tr>
                        <td>{{ $company->name }}</td>
                        <td class="text-right">
                            R$ {{ number_format($company->subscription_limit, 2, ',', '.') }}
                        </td>
                        <td class="text-right">
                            R$ {{ number_format($company->consumption, 2, ',', '.') }}
                        </td>
                        <td class="text-right">
                            <form role="form" action="{{ route('admin.destroy', $company->id) }}" method="post">
                                {{ csrf_field() }}
                                {{ method_field('delete') }}
                                <a href="{{ route('admin.edit', $company->id) }}" class="btn btn-default">Editar</a>
                                <button type="submit" class="btn btn-danger">Excluir</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endempty

resources/views/company/employee.blade.php
@extends ('company.layouts.main')

@section('page_heading','Funcionário')

@section('section')

    <div class="col-sm-12">
        <div class="row">
            <div class="col-lg-12 margin-bottom-20">
                @isset($id)
                    <form role="form" action="{{ route('company.update', $id) }}" method="post">
                @else
                    <form role="form" action="{{ route('company.store') }}" method="post">
                @endisset

                    {{ csrf_field() }}

                    @isset($id)
                        {{ method_field('put') }}
                    @endisset

                    <div class="form-group">
                        <label for="name">Nome</label>
                        <input id="name" name="name" value="{{ $name ?? old('name') }}" class="form-control" maxlength="100" required>
                    </div>
                    <div class="form-group">
                        <label for="cpf">CPF</label>
                        <input id="cpf" name="cpf" value="{{ $cpf ?? old('cpf') }}" class="form-control" maxlength="11" required>
                    </div>
                    <div class="form-group">
                        <label for="consumption_limit">Limite mensal</label>
                        <div class="input-group">
                            <span class="input-group-addon">R$</span>
                            <input type="number" id="consumption_limit" name="consumption_limit" value="{{ $consumption_limit ?? old('consumption_limit') }}" class="form-control" step="0.01" min="1" max="100000" maxlength="6" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="registration_number">Número de matrícula</label>
                        <input id="registration_number" name="registration_number" value="{{ $registration_number ?? old('registration_number') }}" class="form-control" maxlength="14" required>
                    </div>
                    <div class="form-group">
                        <label for="password">Senha</label>
                        <input type="password" id="password" name="password" class="form-control" minlength="6" maxlength="8" {{ empty($id) ? 'required' : '' }}>
                    </div>
                    <div class="form-group">
                        <label for="password_confirmation">Confirmação de senha</label>
                        <input type="password" id="password_confirmation" name="password_confirmation" class="form-control" minlength="6" maxlength="8" {{ empty($id) ? 'required' : '' }}>
                    </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>
                    <a class="btn btn-default" href="{{ route('company.index') }}">Cancelar</a>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/company/layouts/main.blade.php
@extends('layouts.app')

@section('body')
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ route('company.index') }}">
                    <img src="{{ asset('img/LOGO_ASSINATURA.svg') }}" class="navbar-logo">
                    <b>VALE</b>
                </a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> {{ ucwords(Auth::user()->name) }} <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="{{ route('company.logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                                <i class="fa fa-sign-out fa-fw"></i> Logout
                            </a>
                        </li>
                        <form id="logout-form" action="{{ route('company.logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </ul>
                </li>
            </ul>

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li {{ (Request::is('*company') ? 'class="active"' : '') }}>
                            <a href="{{ route('company.index') }}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li {{ (Request::is('*create') ? 'class="active"' : '') }}>
                            <a href="{{ route('company.create') }}"><i class="fa fa-edit fa-fw"></i> Cadastro funcionários</a>
                        </li>
                        <li {{ (Request::is('*reports') ? 'class="active"' : '') }}>
                            <a href="{{ route('company.reports') }}"><i class="fa fa-bar-chart-o fa-fw"></i> Transações</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">

                    <h1 class="page-header">@yield('page_heading')</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>

            @if (session('info'))
                <div class="alert alert-info">
                    {{ session('info') }}
                </div>
            @endif

            @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif

            @if (session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
            @endif

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="row">
                @yield('section')
            </div>
            <!-- /#page-wrapper -->
        </div>
    </div>
@endsection

resources/views/company/widgets/index.blade.php
@if(!$employees->count())
    <div class="alert alert-info">Nenhum registro encontrado!</div>
@else
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th class="col-sm-6">Nome</th>
                    <th class="col-sm-2 text-right">Limite mensal</th>
                    <th class="col-sm-2 text-right">Saldo disponível</th>
                    <th class="col-sm-2"></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($employees as $employee)
                    <tr>
                        <td>{{ $employee->name }}</td>
                        <td class="text-right">
                            R$ {{ number_format($employee->consumption_limit, 2, ',', '.') }}
                        </td>
                        <td class="text-right">
                            R$ {{ number_format($employee->remaining_consumption_limit, 2, ',', '.') }}
                        </td>
                        <td class="text-right">
                            <form role="form" action="{{ route('company.destroy', $employee->id) }}" method="post">
                                {{ csrf_field() }}
                                {{ method_field('delete') }}
                                <a href="{{ route('company.edit', $employee->id) }}" class="btn btn-default">Editar</a>
                                <button type="submit" class="btn btn-danger">Excluir</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endempty